### ISSUE TITLE
mybatis-r2dbc-spring

### ISSUE THREAD

**Issue by hongbofan** [chenggangpro/reactive-mybatis-support#134]
有完整的demo可以看看吗

**Comment by chenggangpro** [comment]
There is an example project  https://github.com/chenggangpro/reactive-mybatis-support-examples. 
You can check out `README.md`file in current repository for more information.

**Comment by chenggangpro** [comment]
The original configuration setting is moved to a new namespace `r2dbc.mybatis.configuration` .See this file [application.yml](https://github.com/chenggangpro/reactive-mybatis-support/blob/main/mybatis-r2dbc-spring/src/test/resources/application.yml).I test the application with `SL4J` and `Logback`,  it worked fine. 
Since I only changed the source code associated with the connection and didn't change the others , please try setting configurations under new namespace ,and see whether it works probably.

**Comment by hongbofan** [comment]
> 
yml改成如下
r2dbc:
  mybatis:
    mapper-locations: classpath:mapper/*.xml
  configuration: # 日志配置，控制台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
仍无法在控制台输出
我去源码R2dbcMybatisConfiguration 看了一下，似乎并没有log-impl 字段可以设置，只能用SL4J或者Logback吗？

**Comment by chenggangpro** [comment]
I think I missed some code when I copy original Spring-Mybatis's source code to `R2dbcMybatisAutoConfiguration`.You can use a `R2dbcMybatisConfigurationCustomizer` bean to set log-impl manually for now.
FYI: The [org.apache.ibatis.logging.LogFactory](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/logging/LogFactory.java) would search classpath to determine which log adapter should be used. I just use it in current project, nothing more.

**Comment by hongbofan** [comment]
> configuration

是我的yml的问题，configuration层级放错了。其次我在R2dbcMybatisConfiguration 的父类Configuration发现了log-impl，感谢你的回答。
